language: dart
dist: bionic
jobs:
  include:
    - stage: run tests
      dart: stable
      before_install:
        - |
          echo "
          loopback_users = none
          listeners.ssl.default = 5671

          ssl_options.cacertfile = /certs/ca_certificate.pem
          ssl_options.certfile   = /certs/server_certificate.pem
          ssl_options.keyfile    = /certs/server_key.pem
          ssl_options.verify     = verify_peer
          ssl_options.fail_if_no_peer_cert = false
          " >  /tmp/rabbitmq.conf
        - docker run -d --mount type=bind,source="$(pwd)"/test/lib/mocks/certs,target="/certs" --mount type=bind,source="/tmp/rabbitmq.conf",target="/etc/rabbitmq/rabbitmq.conf" -p 5671:5671 -p 5672:5672 rabbitmq:3.7.20
        - sleep 3
      install:
        - gem install coveralls-lcov
      script:
        - export PATH=$PATH:"${TRAVIS_HOME}/.pub-cache/bin"
        - pub get
        - dart format --set-exit-if-changed .
        - dartanalyzer --fatal-warnings --fatal-hints --fatal-lints ./
        - AMQP_RUN_TLS_TESTS=true dart --pause-isolates-on-exit --disable-service-auth-codes --enable-vm-service=9292 test/run_all.dart &
        - pub global activate coverage
        - pub global run coverage:collect_coverage --port=9292 --out=coverage/coverage.json --wait-paused --resume-isolates
        - pub global run coverage:format_coverage --lcov --in=coverage/coverage.json --out=coverage/lcov.info --packages=.packages --report-on=lib --check-ignore
      after_success:
        - coveralls-lcov coverage/lcov.info
cache:
  directories:
    - "${TRAVIS_HOME}/.pub-cache"
