name: dart_amqp
description: >
  Dart AMQP client implementing protocol version 0.9.1
version: 0.1.5
author: Achilleas Anagnostopoulos
homepage: https://github.com/achilleasa/dart_amqp
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  logging: ^1.0.1
dev_dependencies:
  test: ^1.17.5
  mockito: ^5.0.9
  http: ^0.13.3
  xml: ^5.1.1
  lints: ^1.0.1
